version: '3'
services:
    web:
        image: nginx:1.15.6
        ports:
            - "18080:80"
            - "443:443"
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - .:/var/www/html
        depends_on:
            - app
        container_name: lalavel_web
    app:
        image: php:7.4-fpm
        volumes:
            - .:/var/www/html
        container_name: lalavel_app